name: Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: npm i
      - run: npm run test
      - run: npm run lint
      - run: npm run build
