name: CI
env:
  DB_HOST: localhost
  DB_PORT: 3306
  DB_USERNAME: root
  DB_PASSWORD: password
  DB_NAME: template-express
  NODE_ENV: dev
  SEND_CONFIRMATION_EMAIL_QUEUE: teste
  JWT_SECRET: 4b0975fedd303ce4ebcaff1c845e99c22ebc10ea72b31cad5c5e637423d0759b
  REDIS_HOST: teste
  REDIS_PORT: 123
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node 18.16
        uses: actions/setup-node@v3
        with:
          node-version: 18.16

      - name: Environment variables to Dotenv
        uses: CallePuzzle/envvar-to-dotenv-action@v1.1.5
        with:
          variableNames: DB_HOST,DB_PORT,DB_USERNAME,DB_PASSWORD,DB_NAME,NODE_ENV,SEND_CONFIRMATION_EMAIL_QUEUE,JWT_SECRET,REDIS_HOST,REDIS_PORT

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Run lint
        run: npm run lint

      - name: Typescript build
        run: npm run build
  securityscan:
    runs-on: ubuntu-latest
    name: njsscan check
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '.'
